// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEXkRtlLH_j4Rezn83B6artplSiJ5bqJs',
    appId: '1:533231650516:web:ecc1f724a2831042461d41',
    messagingSenderId: '533231650516',
    projectId: 'febar-project',
    authDomain: 'febar-project.firebaseapp.com',
    storageBucket: 'febar-project.appspot.com',
    measurementId: 'G-J367R65PBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBm_O54Op7d638blN7BYUpPCPhN2LSeI',
    appId: '1:533231650516:android:1f79a25283f4bb37461d41',
    messagingSenderId: '533231650516',
    projectId: 'febar-project',
    storageBucket: 'febar-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_SluNrjg-ywfLzScHBxeMmzJwfhRiYlk',
    appId: '1:533231650516:ios:888e427d30db7676461d41',
    messagingSenderId: '533231650516',
    projectId: 'febar-project',
    storageBucket: 'febar-project.appspot.com',
    iosBundleId: 'com.febartravel.febarproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_SluNrjg-ywfLzScHBxeMmzJwfhRiYlk',
    appId: '1:533231650516:ios:888e427d30db7676461d41',
    messagingSenderId: '533231650516',
    projectId: 'febar-project',
    storageBucket: 'febar-project.appspot.com',
    iosBundleId: 'com.febartravel.febarproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEXkRtlLH_j4Rezn83B6artplSiJ5bqJs',
    appId: '1:533231650516:web:0627d3630c78f2a9461d41',
    messagingSenderId: '533231650516',
    projectId: 'febar-project',
    authDomain: 'febar-project.firebaseapp.com',
    storageBucket: 'febar-project.appspot.com',
    measurementId: 'G-0F3408D83G',
  );
}
